version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: disco/disco-daemon-dev
    command: hypercorn --bind 0.0.0.0:6543 disco.app:app
    ports:
      - 6543:6543
    volumes:
      - .:/disco/app:cached
      - ./data:/disco/data
      - /disco/app/disco.egg-info

networks:
  default:
    name: disco_default
