[project]
name = "disco"
dynamic = ["version"]

[tool.setuptools]
packages = ["disco"]

[tool.setuptools.dynamic]
version = {attr = "disco.__version__"}

[project.scripts]
disco_worker = "disco.worker:main"
disco_init = "disco.scripts.init:main"
disco_init_db = "disco.scripts.init:init_database_script"
disco_update = "disco.scripts.update:main"
disco_set_core_logging = "disco.scripts.setcorelogging:main"
disco_leave_swarm = "disco.scripts.leave_swarm:main"
disco_pull_backup = "disco.scripts.pull_backup:main"
disco_restore = "disco.scripts.restore:main"
disco_migrate_caddy_storage = "disco.scripts.migrate_caddy_storage:main"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I"]

[tool.mypy]
ignore_missing_imports = true
