CADDY_VERSION = "2.7.6"
SQLALCHEMY_DATABASE_URL = "sqlite:////disco/data/disco.sqlite3"
SQLALCHEMY_ASYNC_DATABASE_URL = "sqlite+aiosqlite:////disco/data/disco.sqlite3"
DISCO_TUNNEL_VERSION = "1.0.0"
BUSYBOX_VERSION = "1.37.0"
